Fix error of "The test(shell-binder) is not found"
http://validation.linaro.org/lava-server/scheduler/job/45842/log_file
The real reason is because the undefined PATTERN is used:
Traceback (most recent call last):
  File "/srv/lava/.cache/eggs/lava_android_test-0.16.1-py2.7.egg/lava_android_test/provider.py", line 104, in load_test
      serial=serial)
  File "/srv/lava/.cache/eggs/lava_android_test-0.16.1-py2.7.egg/lava_android_test/provider.py", line 234, in load_test
      parser=testdef.AndroidSimpleTestParser(PATTERN),
NameError: global name 'PATTERN' is not defined